import {
  SiCsharp,
  SiDart,
  SiPython,
  SiLatex,
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiSass,
  SiBootstrap,
  SiTailwindcss,
  SiDjango,
  SiFlask,
  SiFlutter,
  SiPostgresql,
  SiNginx,
  SiPostman,
  SiHeroku,
  SiDocker,
  SiGithubactions,
  SiLinux,
  SiDigitalocean,
  SiJetbrains,
  SiGnubash,
  SiAnsible,
  SiCisco,
  SiVmware,
  SiPaloaltosoftware,
  SiMarkdown,
  SiReact,
  SiPycharm,
  SiPytest,
  SiSqlite,
  SiGatsby,
  SiTerraform,
  SiGit,
  SiGithub,
  SiVim,
  SiJest
} from "react-icons/si";

const iconMap = {
  // SiCsharp: { icon: SiCsharp, label: "C#" },
  SiDart: { icon: SiDart, label: "Dart" },
  SiPython: { icon: SiPython, label: "Python" },
  SiLatex: { icon: SiLatex, label: "LaTeX" },
  SiJavascript: { icon: SiJavascript, label: "JavaScript" },
  SiTypescript: { icon: SiTypescript, label: "TypeScript" },
  SiHtml5: { icon: SiHtml5, label: "HTML5" },
  SiCss3: { icon: SiCss3, label: "CSS3" },
  SiSass: { icon: SiSass, label: "SASS" },
  SiBootstrap: { icon: SiBootstrap, label: "Bootstrap" },
  SiTailwindcss: { icon: SiTailwindcss, label: "Tailwind CSS" },
  SiDjango: { icon: SiDjango, label: "Django" },
  SiFlask: { icon: SiFlask, label: "Flask" },
  SiFlutter: { icon: SiFlutter, label: "Flutter" },
  SiPostgresql: { icon: SiPostgresql, label: "PostgreSQL" },
  SiNginx: { icon: SiNginx, label: "NGINX" },
  SiPostman: { icon: SiPostman, label: "Postman" },
  SiHeroku: { icon: SiHeroku, label: "Heroku" },
  SiDocker: { icon: SiDocker, label: "Docker" },
  SiGithubactions: { icon: SiGithubactions, label: "GitHub Actions" },
  SiLinux: { icon: SiLinux, label: "Linux" },
  SiDigitalocean: { icon: SiDigitalocean, label: "DigitalOcean" },
  SiJetbrains: { icon: SiJetbrains, label: "JetBrains" },
  SiGnubash: { icon: SiGnubash, label: "GNU Bash" },
  SiAnsible: { icon: SiAnsible, label: "Ansible" },
  SiCisco: { icon: SiCisco, label: "Cisco" },
  SiVmware: { icon: SiVmware, label: "VMware" },
  SiPaloaltosoftware: { icon: SiPaloaltosoftware, label: "Palo Alto" },
  SiMarkdown: { icon: SiMarkdown, label: "Markdown" },
  SiReact: { icon: SiReact, label: "React" },
  SiPycharm: { icon: SiPycharm, label: "PyCharm" },
  SiPytest: { icon: SiPytest, label: "Pytest" },
  // SiPlaywright: { icon: SiPlaywright, label: "Playwright" },
  SiSqlite: { icon: SiSqlite, label: "SQLite" },
  // SiPowershell: { icon: SiPowershell, label: "PowerShell" },
  SiGatsby: { icon: SiGatsby, label: "Gatsby" },
  SiTerraform: { icon: SiTerraform, label: "Terraform" },
  SiGit: { icon: SiGit, label: "Git" },
  SiGithub: { icon: SiGithub, label: "GitHub" },
  SiVim: { icon: SiVim, label: "Vim" },
  SiJest: { icon: SiJest, label: "Jest" }
};

export default iconMap;
