import {
    SiBootstrap, SiCss3,
    SiDigitalocean, SiDjango,
    SiDocker, SiFlask, SiGatsby,
    SiGit,
    SiGnubash,
    SiGrafana, SiHeroku, SiHtml5,
    SiInfluxdb, SiJavascript, SiLinux, SiMarkdown,
    SiMqtt, SiNginx,
    SiOpenssl, SiPostgresql, SiPytest,
    SiPython, SiReact,
    SiTelegraph, SiTerraform, SiTypescript, SiWebpack,
    SiDart,
    SiLatex,
    SiSass,
    SiTailwindcss,
    SiFlutter,
    SiPostman,
    SiGithubactions,
    SiJetbrains,
    SiAnsible,
    SiCisco,
    SiVmware,
    SiPaloaltosoftware,
    SiPycharm,
    SiSqlite,
    SiGithub,
    SiVim,
    SiJest,
} from "react-icons/si";

export const projects = [
    {
        title: "DotCertify",
        yearStart: 2026,
        description: "A Python playground for exploring X.509 PKI workflows — generating keys, building CSRs, operating a local CA, signing certificates, and validating certificate chains using the cryptography library.",
        image: "/graphics/projects/dotcertify.png",
        link: "https://github.com/blue-hexagon/DotCertify",
        tags: ["PKI", "X.509", "Cryptography"],
        icons: [SiPython, SiGit, SiOpenssl],
        packageAvailable: null,
        complexity: "moderate",
        source: "open",
        id: -6
    },
    {
        title: "MQ-Hero",
        yearStart: 2026,
        description: "A distributed IoT simulation and management platform built around MQTT — featuring policy-driven topic modeling, multi-tenant schemas, and observability integration (Telegraf, InfluxDB, Grafana).",
        image: "/graphics/projects/mq_hero.png",
        link: "/graphics/projects/pdf/dt_svendeprove_presentation2026-02-12-4601h6dakn21.pdf",
        tags: ["IoT", "MQTT", "Distributed Systems"],
        icons: [SiPython, SiDocker, SiGnubash, SiMqtt, SiGrafana, SiTelegraph, SiInfluxdb],
        packageAvailable: null,
        complexity: "advanced",
        source: "open",
        id: -5
    },
    {
        title: "manjana.dev",
        yearStart: 2025,
        description: "A Gatsby + MDX technical platform showcasing deep dives into systems, encoding, networking, and infrastructure — powered by custom React components and advanced UI tooling.",
        image: "/graphics/projects/manjana_dev.png",
        link: "https://manjana.dev",
        tags: ["Web Application"],
        icons: [SiMarkdown, SiGatsby, SiJavascript, SiTypescript, SiReact, SiGit],
        packageAvailable: null,
        complexity: "advanced",
        source: "open",
        id: -4
    },
    {
        title: "HyperSnitch",
        yearStart: 2025,
        yearEnd: 2025,
        description: "An auto-deployable website monitoring tool with built-in SMTP alerts. Detects when specific strings are added or removed from target pages.",
        image: "/graphics/projects/hypersnitch.png",
        link: "https://github.com/blue-hexagon/HyperSnitch",
        tags: ["Monitoring", "Automation", "Web Scraping"],
        icons: [SiPython, SiGnubash, SiDigitalocean, SiPytest, SiGit],
        packageAvailable: null,
        complexity: "moderate",
        source: "open",
        id: -3
    },
    {
        title: "LendIT.Pro",
        yearStart: 2023,
        yearEnd: 2024,
        description: "A multi-tenant asset and loan management platform for organizations to track and manage IT equipment lending. Built with Django and PostgreSQL with RBAC staff management, automated PDF receipts, and infrastructure automation via Docker and Terraform.",
        image: "/graphics/projects/lendit.png",
        link: null,
        tags: ["Web Application", "Asset Management", "Django"],
        icons: [SiPython, SiDjango, SiPostgresql, SiDocker, SiTerraform, SiJavascript],
        packageAvailable: null,
        complexity: "complex",
        source: "closed",
        id: -2
    },
    {
        title: "Armada (Cthulhu)",
        yearStart: 2022,
        description: "A research project exploring decentralized command-and-control architecture for distributed security testing, featuring YAML-driven orchestration, peer-to-peer task propagation, and scalable execution across coordinated nodes.",
        image: "/graphics/projects/armada.png",
        link: "",
        tags: ["Cybersecurity", "Distributed Systems", "Automation", "Closed Source"],
        icons: [SiPython, SiGit],
        packageAvailable: null,
        complexity: "complex",
        source: "closed",
        id: -1
    },
    {
        title: "BashLAMP",
        yearStart: 2022,
        yearEnd: 2022,
        description: "One-command provisioning of a Rocky Linux LAMP stack with WordPress and secure FTP.",
        image: "/graphics/projects/bashlamp.png",
        link: "https://github.com/blue-hexagon/BashLAMP",
        tags: ["Bash", "LAMP", "vsftpd", "Linux"],
        icons: [SiLinux, SiGnubash, SiGit],
        packageAvailable: null,
        complexity: "simple",
        source: "open",
        id: 0
    },
    {
        title: "PyInit",
        yearStart: 2024,
        description: "A lightweight Python project bootstrap template that provides instant setup of development tooling, formatting, linting, and testing workflows using Poetry, pre-commit hooks, and automated task runners.",
        image: "/graphics/projects/pyinit.png",
        link: "https://github.com/blue-hexagon/pyinit",
        tags: ["Python", "Developer Tooling"],
        icons: [SiPython, SiGit],
        packageAvailable: null,
        complexity: "tiny",
        source: "open",
        id: 1
    },
    {
        title: "TS-Calculator",
        yearStart: 2022,
        yearEnd: 2022,
        description: "A custom TypeScript calculator built from scratch with full keyboard input handling and a modular UI architecture.",
        image: "/graphics/projects/ts_calculator.gif",
        link: "https://github.com/blue-hexagon/TS-Calculator",
        tags: ["TypeScript", "Webpack"],
        icons: [SiTypescript, SiWebpack, SiGit],
        packageAvailable: null,
        complexity: "simple",
        source: "open",
        id: 2
    },
    {
        title: "JHHuse",
        yearStart: 2021,
        yearEnd: 2022,
        description: "A Django-powered website for a homeowners association, featuring document management and member information updates.",
        image: "/graphics/projects/jhhuse_dk.png",
        link: "https://www.jhhuse.dk/",
        tags: ["Django", "CMS", "Full Stack"],
        icons: [SiPython, SiDjango, SiBootstrap, SiNginx, SiHtml5, SiDigitalocean, SiGit],
        packageAvailable: null,
        complexity: "simple",
        source: "closed",
        id: 3
    }, {
        title: "WinScraper",
        yearStart: 2021,
        yearEnd: 2022,
        description: "Windows system reconnaissance CLI and library in Python.",
        image: "/graphics/projects/winscraper.png",
        link: "/projects/hypersnitch",
        tags: ["Windows", "System Recon", "Python"],
        icons: [SiPython, SiGit],
        packageAvailable: null,
        complexity: "simple",
        source: "open",
        id: 4
    },

    {
        title: "Cheatsheet.wtf",
        yearStart: 2021,
        yearEnd: 2021,
        description: "A modernized evolution of ShellMagic.xyz — interactive and searchable terminal cheatsheet platform.",
        image: "/graphics/projects/cheatsheet_wtf.png",
        link: "https://web.archive.org/web/20250426052813/https://www.cheatsheet.wtf/",
        tags: ["Bash", "Vim", "Linux", "Git"],
        icons: [SiPython, SiFlask, SiGit, SiHeroku, SiHtml5, SiCss3, SiJavascript],
        packageAvailable: null,
        complexity: "moderate",
        source: "closed",
        id: 5
    },
    {
        title: "ShellMagic.Xyz",
        yearStart: 2020,
        yearEnd: 2020,
        description: "A minimalist Bash cheatsheet site — my first serious web project.",
        image: "/graphics/projects/shellmagic_xyz.png",
        link: "https://web.archive.org/web/20200411230156/https:/shellmagic.xyz/",
        tags: ["Bash", "Webarchived"],
        icons: [SiHtml5, SiCss3],
        packageAvailable: null,
        complexity: "tiny",
        source: "open",
        id: 6
    },
];

